### ISSUE TITLE
媽媽問我為什麼跪著發 issue

### ISSUE THREAD

**Issue by yuanchieh-at** [Yu-Jack/shop-ddd-go#1]
比對老師的 repo，有幾點想要請教，不確定是不是因應 Golang 實作的調整

1. repository 的 interface 定義擺在 usecase 下好像會比較符合 Clean Architecture 的設計
https://gitlab.com/-/ide/project/TeddyChen/dddcleankanban/tree/master/-/board/src/main/java/ntut/csie/sslab/kanban/usecase/board/BoardRepository.java/

https://github.com/Yu-Jack/shop-ddd-go/blob/0848425a3d000b9b79597bd59a1b5dbc3cbf84d9/services/order/repository/repository.go#L9

2. 單純好奇檔案路徑的設計
https://gitlab.com/-/ide/project/TeddyChen/dddcleankanban/tree/master/-/board/src/main/java/ntut/csie/sslab/kanban/usecase/card/
我看老師的 usecase folder 設計會是
```
{entity}
    |- {usecase}
       |- interface
       |- impl
   |- repo_interface
   |- dto
```
  
https://github.com/Yu-Jack/shop-ddd-go/tree/main/services/order/usecase
以目前的設計是希望對外 Usecase interface, 然後不同的 entity 實作在各自的路徑如 usecase/order.go，未來可能多個 user 相關直接變成 usecase/user.go，然後外部統一用 Usecase.CreateUser 之類的呼叫囉？
在想如果讓 usecase 都各自宣告，不要最外層有一個共用的 interface 會不會比較獨立
```golang
# /services/order/usecase/order/create_order.go
package create_order_usecase
interface CreateOrderUseCase {
   Execute(CreateOrderInput) CreateOrderOutput
}

func New(repo Repo) CreateOrderUseCase {
    return &executeFunc{repo}
}

# /services/order/usecase/order/create_order_usecase_impl.go
package create_order_usecase
struct executeFunc {
     repo Repo
}

func (f* executeFunc) Execute(in CreateOrderInput) CreateOrderOutput{
	xxxxx
}  

# 使用
create_order_usecase.New().Execute(...)
```

3. domain event 好像是獨立於 entity
https://gitlab.com/-/ide/project/TeddyChen/dddcleankanban/tree/master/-/board/src/main/java/ntut/csie/sslab/kanban/entity/model/card/

https://github.com/Yu-Jack/shop-ddd-go/blob/0848425a3d000b9b79597bd59a1b5dbc3cbf84d9/services/order/entity/order.go#L23 

--------------

剛剛看 teddy 在 entity 直接發 domain event，這邊有個蠻有趣的設計
https://gitlab.com/-/ide/project/TeddyChen/dddcleankanban/tree/master/-/board/src/main/java/ntut/csie/sslab/kanban/entity/model/card/Card.java/#L34

當 Card 物件 new 出來就會有 domain event，但這有點怪因為 repo 查詢後要轉回 entity 也會需要 new，他的做法是把它清掉 XD
https://gitlab.com/-/ide/project/TeddyChen/dddcleankanban/tree/master/-/board/src/main/java/ntut/csie/sslab/kanban/adapter/gateway/repository/springboot/card/CardMapper.java/#L35

**Comment by Yu-Jack** [comment]
## 回答 1

可以，我只需要把以下 struct 中的 repo 介面改成是在 usecase 底下的 repo interface 即可，然後原本 `repository` > repository.go 就只要單純回傳 repo 就好，不要回傳介面。這樣到時候配合 aggregate root 的時候，就可以限制只有 order 這個 aggregate 能夠去呼叫所有 db 的操作，這方式不錯。推推
```go
type usecase struct {
	repo     repository.Repository
	eventBus *dddcore.EventBus
}
```

## 回答 2

這問題跟前面一個也一樣，當時寫只有針對 order usecase 去寫，綜合你的概念我覺得會有以下幾種

--這是第一種

```
|--services
|--|--order --> 這裡算是 order 的 project root，是可以被獨立開發，所以不一定叫做 order，可以是 shop-order
|--|--|--order folder -> domain
|--|--|--|--usecase folder -> package order_usecase
|--|--|--|--|-- create_order.go
|--|--|--|--|-- update_order.go
|--|--|--|--repository folder
|--|--|--order_item folder -> domain
|--|--|--|--usecase folder -> package order_item_usecase
|--|--|--|--|-- create_order_item.go
|--|--|--|--|-- update_order_item.go
|--|--|--|--repository
```

order_usecase.New() -> 包含 create update，但實際程式可以分開，只是我不確定這種 folder 叫做 usecase，但是 package name 改成 order_usecase 是不是 golang 裡面建議的做法？


--這是第二種

```
|--services
|--|--order folder
|--|--|--order folder -> domain, package order
|--|--|--|--usecase_create_order.go
|--|--|--|--usecase_update_order.go
|--|--|--|--repository_create_order.go
|--|--|--order_item folder -> domain, package order_item
|--|--|--|--usecase_create_order_item.go
|--|--|--|--usecase_update_order_item.go
|--|--|--|--repository_create_order.go
```

使用就是 order.NewUsecase() -> 也是包含 create update，這個 package name 就跟 folder name 是一致。

--這是第三種

```
|--services
|--|--order
|--|--|--order folder -> domain
|--|--|--|--usecase folder 
|--|--|--|--|-- create_order folder -> package create_order_usecase
|--|--|--|--|-- update_order folder -> package update_order_usecase
|--|--|--|--repository folder
|--|--|--order_item folder -> domain
|--|--|--|--usecase folder -> package order_item_usecase
|--|--|--|--|-- create_order_item folder -> package create_order_usecase
|--|--|--|--|-- update_order_item folder -> package update_order_uasecase
|--|--|--|--repository
```

我個人覺得第三種蠻怪的，有一種切割太多，然後把 java folder strcuture 硬套過來，沒利用到 go 的特性的感覺？


我個人還在思考有沒有第四種，訴求如下
- 希望讓 package name 等於 folder name 這樣比較不會誤導看的人
- 同時也希望不要在一個 folder 塞了一堆檔案以及不要太多 folder，只是我看 go 的專案好像蠻多就是底下一堆檔案 XD
- 我要先 package by feature 再 package by layer，這樣做就類似上面第一種，但就會違反我的第一點，但若是第一點是沒問題的話，那我覺得蠻 ok XD

題外話，如果你在 order/create_order.go，然後要把 create_order.go 的 package 定義成 create_order_usecase，那這樣其他 同樣在 order/modify_order.go 就不太適合，因為他是叫 modify_order.go，主要限制是同個 folder 底下的 package name 要都是一樣，變成說要在獨立建立出新的 modify_order 專用的資料夾，這我覺得在 go 裡面似乎有點怪怪的？

## 回答 3

我來解釋為啥我合併 XDD，event 我本來想全部定義在 evenhandler，但因為我 evenhandler 會 import usecase，就變成，我不能在 usercase import evenhandler 裡面我定義好的 event.go，就會造成 cycle import，所以當下先決定合併再一起。

另外我再更一開始是打算在 NewOrder 時，就直接建立好 domain event，但後來我發現第一個是資料我不太好塞，原因是我想塞 json string 到 kafka 去，所以再丟到 event bus 之前我要先 toJson，所以才特別切開，這段我也還在找比較適合的做法。

## 題外話

我覺得 https://github.com/Ptt-official-app/Ptt-backend/issues/16 這應該可以拿來參考參考

**Comment by Yu-Jack** [comment]
Btw, 這應該也可以參考一下 https://github.com/Ptt-official-app/Ptt-backend/issues/16

**Comment by yuanchieh-at** [comment]
OKOK~ 關於第二點我想錯方向了，不用一個 usecase 一個 package 否則就拆太細了
想了一下 folder 如果跟 package 掛鉤，第一層放 bounded context 我覺得沒什麼問題
但第二層要用 entity 拆分或是以 layer 拆分我就不太確定，如第一個設計
```
|--services
|--|--order --> 應該比較算 Bounded Context ? 獨立部署的最小單位
|--|--|--order folder -> 還是這一層才是 Bounded Context ? 但看起來比較像 entity 或 aggregate root，不太確定 domain 是指哪一個部分
|--|--|--|--usecase folder -> package order_usecase
|--|--|--|--|-- create_order.go
|--|--|--|--|-- update_order.go
|--|--|--|--repository folder
```

如果學老師第二層以 layer 拆分，我的設想會是
```
|--services
|--|--order 
|--|--|--entity -> pkg: order_entity
|--|--|--|--order.go
|--|--|--|--user.go
|--|--|--usecase -> pkg: order_usecase
|--|--|--|--create_order.go
|--|--|--|--update_order.go
|--|--|--|--update_user.go
|--|--|--adapter
```
by layer 好處是 usecase 下可能會用到多個 entity，也比較直觀對應到不同的層級，對比以 entity 為第二層架構就比較難有這樣的關係

這樣不知道好不好

**Comment by Yu-Jack** [comment]
> OKOK~ 關於第二點我想錯方向了，不用一個 usecase 一個 package 否則就拆太細了 想了一下 folder 如果跟 package 掛鉤，第一層放 bounded context 我覺得沒什麼問題 但第二層要用 entity 拆分或是以 layer 拆分我就不太確定，如第一個設計
> 
> ```
> |--services
> |--|--order --> 應該比較算 Bounded Context ? 獨立部署的最小單位

你想成這個 order 是單獨的一個 git repo 就好，所以他名字可以是 shop-order，底下才是真正開始要分類的地方，所以那層可以忽略，對比的話很像老師定義的資料結構最外面的那層

```
account
board
dddcore
```

你的設想其實跟我現在資料夾架構是一樣的，你 cd 到 services/order 裡面去看，把 services/order 當作 project root 去看就會發現其實差不多，只是現在我所有 usecase 都寫在 order.go 底下而已，還沒拆成 create_order.go or update_order.go。

但如果你 usecase pkg 定義成 order_usecase，未來 create_order_item.go 擺在他下面就會顯得奇怪，usecase pkg 單純就 usecase 應該會比較適合，基本上就是所有關於 order 有關係的 usecase 都在裡面。

目前覺得比較大的問題會是，當我有新的 usecase 跟 order 有關，但又不是 order 本身的話，怎麼擺放資料夾比較適合，如果是用檔案名稱區分的話，我覺得其實很合理，但缺點就是可能會有海量的檔案，變成只能用 prefix 去處理。

BTW，可以用這個畫架構 https://tree.nathanfriend.io/

**Comment by Yu-Jack** [comment]
@yuanchieh-at 我發現我們要用 alias 就好，pkg 跟 folder name 就可以一樣，在引用的時候 (圖右邊) 再去處理 alias 就可以很清楚切開了，這樣全部都可以叫做 usecase 就不會有問題，另外其實最外層叫做 order 裡面就不用 create_order.go，直接叫 create.go 就 ok 了。

![image](https://user-images.githubusercontent.com/6960289/165455267-c650a545-aa12-49bb-8695-4d9d360db4d5.png)
